permalink: /:categories/:title.html
baseurl: ""
url: "http://www.portraitsfrom.photos"
#url: "http://localhost:4000"
full_name: "Portraits from Photos"
first_name: "Portraits"
last_name: "from Photos"
email: "hello@portraitsfrom.photos"
blog_title: "portraits from photos"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "portraitsfromphotos"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: ""
github: "veromary"
facebook: ""
linkined_url: ""
